services:
  peeper-proxy:
    build: ./proxy
    container_name: peeper-proxy
    ports:
      - "3001:3001"
    networks:
      - peeper-network
    volumes:
      - ./config/workspace:/config/workspace:ro
      - ./diffs:/diffs
      - ./proxy:/app # remove after dev
    depends_on:
      - code-server
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=wouldntyouliketoknow
      - DEFAULT_WORKSPACE=/config/workspace
      - USE_HTTPS=false
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
    networks:
      - peeper-network
    restart: unless-stopped

networks:
  peeper-network:
    external: true